services:
    openroot.clientContext.entity.client.repository:
        class: Doctrine\Common\Persistence\ObjectRepository
        factory_service: doctrine
        factory_method: getRepository
        arguments: ["Openroot\Bundle\ClientContextBundle\Entity\Client" ]

    openroot.clientContext.entity.clientHttpContext.repository:
        class: Doctrine\Common\Persistence\ObjectRepository
        factory_service: doctrine
        factory_method: getRepository
        arguments: ["Openroot\Bundle\ClientContextBundle\Entity\ClientHttpContext"]
